using System.Linq;
using TrackFlow.Models.Layout;
using TrackFlow.Services;
using TrackFlow.ViewModels.Editor;
using Xunit;

namespace TrackFlow.Tests;

public class RoutesManagerViewModelRouteMetadataTests
{
    [Fact]
    public void DeleteRoute_ClearsAssignedRouteId_FromRouteMarkersReferencingDeletedRoute()
    {
        var settings = new SettingsManager();
        settings.NewProject();

        var layout = settings.CurrentProject!.Layout;
        layout.Routes.Add(new RouteDefinition { Id = "r-delete", Name = "Mazaná cesta" });
        layout.Routes.Add(new RouteDefinition { Id = "r-keep", Name = "Platná cesta" });

        var affectedMarker = new RouteElement
        {
            Id = "marker-1",
            MarkerKey = "Route",
            SelectedRouteDefinitionId = "r-delete"
        };

        var unaffectedMarker = new RouteElement
        {
            Id = "marker-2",
            MarkerKey = "Route",
            SelectedRouteDefinitionId = "r-keep"
        };

        layout.Elements.Add(affectedMarker);
        layout.Elements.Add(unaffectedMarker);

        var vm = new RoutesManagerViewModel(settings);
        vm.SelectedRoute = Assert.Single(vm.Routes, route => route.Id == "r-delete");

        vm.DeleteRouteCommand.Execute(null);

        Assert.DoesNotContain(layout.Routes, route => route.Id == "r-delete");
        Assert.Null(affectedMarker.SelectedRouteDefinitionId);
        Assert.Equal("r-keep", unaffectedMarker.SelectedRouteDefinitionId);
    }

    [Fact]
    public void ManualRouteSelection_CreatesUserDefinedRoute_WithBlocksSwitchesAndSignals()
    {
        RoutePathfinder.ClearCacheForTests();

        var settings = new SettingsManager();
        settings.NewProject();

        var layout = settings.CurrentProject!.Layout;

        var blockA = new BlockElement
        {
            Id = "blk_a",
            MarkerKey = "Block",
            Label = "A",
            X = 24,
            Y = 24,
            Rotation = 0,
            BlockLengthCells = 4,
            SignalRightId = "sig_a"
        };

        var blockB = new BlockElement
        {
            Id = "blk_b",
            MarkerKey = "Block",
            Label = "B",
            X = 144,
            Y = 24,
            Rotation = 0,
            BlockLengthCells = 4,
            SignalRightId = "sig_b"
        };

        var blockC = new BlockElement
        {
            Id = "blk_c",
            MarkerKey = "Block",
            Label = "C",
            X = 264,
            Y = 24,
            Rotation = 0,
            BlockLengthCells = 4
        };

        var turnout = new TurnoutElement
        {
            Id = "sw_1",
            MarkerKey = "Turnout_R",
            X = 120,
            Y = 24,
            Rotation = 90
        };

        var seg2 = new TrackSegmentElement
        {
            Id = "seg_2",
            MarkerKey = "TrackSegment",
            X = 240,
            Y = 24,
            Rotation = 0
        };

        var sigA = new SignalElement
        {
            Id = "sig_a",
            MarkerKey = "Signal",
            Label = "Na1",
            Rotation = 90
        };

        var sigB = new SignalElement
        {
            Id = "sig_b",
            MarkerKey = "Signal",
            Label = "Na2",
            Rotation = 90
        };

        layout.Elements.Add(blockA);
        layout.Elements.Add(blockB);
        layout.Elements.Add(blockC);
        layout.Elements.Add(turnout);
        layout.Elements.Add(seg2);
        layout.Elements.Add(sigA);
        layout.Elements.Add(sigB);

        var vm = new RoutesManagerViewModel(settings);
        int initial = layout.Routes.Count;

        vm.AddRouteCommand.Execute(null);
        Assert.True(vm.IsManualRouteSelectionActive);

        vm.HandlePreviewBlockClicked("blk_a");
        vm.HandlePreviewBlockClicked("blk_c");

        Assert.False(vm.IsManualRouteSelectionActive);
        Assert.True(layout.Routes.Count >= initial + 1);

        var created = layout.Routes.Last();
        Assert.Equal(RouteDefinitionKind.UserDefinedRoute, created.Kind);
        Assert.False(created.IsAutoGenerated);
        Assert.Equal("blk_a", created.FromBlockId);
        Assert.Equal("blk_c", created.ToBlockId);
        Assert.True(created.BlockIds.Count >= 3);
        Assert.Contains("blk_b", created.BlockIds);
        Assert.Contains("sig_a", created.RouteSignalIds);
        Assert.Contains("sig_b", created.RouteSignalIds);
    }

    [Fact]
    public void GenerateRoutes_FillsDirectionalMetadata_AndRouteSignals()
    {
        RoutePathfinder.ClearCacheForTests();

        var settings = new SettingsManager();
        settings.NewProject();

        var layout = settings.CurrentProject!.Layout;

        var fromBlock = new BlockElement
        {
            Id = "b-from",
            MarkerKey = "Block",
            Label = "B1",
            X = 24,          // cell 1
            Y = 24,          // cell 1
            Rotation = 0,
            BlockLengthCells = 4,
            SignalRightId = "sig-right"
        };

        var toBlock = new BlockElement
        {
            Id = "b-to",
            MarkerKey = "Block",
            Label = "B2",
            X = 144,         // cell 6
            Y = 24,          // cell 1
            Rotation = 0,
            BlockLengthCells = 4
        };

        var connector = new TrackSegmentElement
        {
            Id = "seg-1",
            MarkerKey = "TrackSegment",
            X = 120,         // cell 5
            Y = 24,
            Rotation = 0
        };

        layout.Elements.Add(fromBlock);
        layout.Elements.Add(toBlock);
        layout.Elements.Add(connector);

        var vm = new RoutesManagerViewModel(settings);
        vm.RegenerateRoutesCommand.Execute(null);

        var route = Assert.Single(layout.Routes, r => r.FromBlockId == "b-from" && r.ToBlockId == "b-to");

        Assert.Equal(RouteDirection.Right, route.FromBlockDirection);
        Assert.Equal(RouteDirection.Left, route.ToBlockDirection);
        Assert.Equal(RouteDirection.Right, route.StartNavigationDirection);
        Assert.Equal("Stop", route.SafetyFallbackAspect);
        Assert.Single(route.RouteSignalIds);
        Assert.Equal("sig-right", route.RouteSignalIds[0]);
    }

    [Fact]
    public void GenerateRoutes_CanonicalizesTwoBlockRouteDirection_WhenPathfinderFindsReverseFirst()
    {
        RoutePathfinder.ClearCacheForTests();

        var settings = new SettingsManager();
        settings.NewProject();

        var layout = settings.CurrentProject!.Layout;

        var targetBlock = new BlockElement
        {
            Id = "b5",
            MarkerKey = "Block",
            Label = "Blok 5",
            X = 144,
            Y = 24,
            Rotation = 0,
            BlockLengthCells = 4
        };

        var sourceBlock = new BlockElement
        {
            Id = "b1",
            MarkerKey = "Block",
            Label = "Blok 1",
            X = 24,
            Y = 24,
            Rotation = 0,
            BlockLengthCells = 4,
            SignalRightId = "sig-b1"
        };

        var connector = new TrackSegmentElement
        {
            Id = "seg-b1-b5",
            MarkerKey = "TrackSegment",
            X = 120,
            Y = 24,
            Rotation = 0
        };

        var signal = new SignalElement
        {
            Id = "sig-b1",
            MarkerKey = "Signal",
            Label = "Na1",
            Rotation = 90
        };

        // Intentionally add Blok 5 before Blok 1. Before canonicalization, the
        // first DFS result won and generated the route as Blok 5 -> Blok 1.
        layout.Elements.Add(targetBlock);
        layout.Elements.Add(sourceBlock);
        layout.Elements.Add(connector);
        layout.Elements.Add(signal);

        var vm = new RoutesManagerViewModel(settings);
        vm.RegenerateRoutesCommand.Execute(null);

        var route = Assert.Single(layout.Routes);

        Assert.Equal("b1", route.FromBlockId);
        Assert.Equal("b5", route.ToBlockId);
        Assert.Equal(new[] { "b1", "b5" }, route.BlockIds);
        Assert.Equal(RouteDirection.Right, route.FromBlockDirection);
        Assert.Equal(RouteDirection.Left, route.ToBlockDirection);
        Assert.Equal(RouteDirection.Right, route.StartNavigationDirection);
        Assert.Single(route.RouteSignalIds);
        Assert.Equal("sig-b1", route.RouteSignalIds[0]);
    }

    [Fact]
    public void LoadFromLayout_BackfillsDirectionalMetadata_ForLegacyRoute()
    {
        RoutePathfinder.ClearCacheForTests();

        var settings = new SettingsManager();
        settings.NewProject();

        var layout = settings.CurrentProject!.Layout;

        var fromBlock = new BlockElement
        {
            Id = "b-from",
            MarkerKey = "Block",
            Label = "B1",
            X = 24,
            Y = 24,
            Rotation = 0,
            BlockLengthCells = 4,
            SignalRightId = "sig-right"
        };

        var toBlock = new BlockElement
        {
            Id = "b-to",
            MarkerKey = "Block",
            Label = "B2",
            X = 144,
            Y = 24,
            Rotation = 0,
            BlockLengthCells = 4
        };

        var connector = new TrackSegmentElement
        {
            Id = "seg-1",
            MarkerKey = "TrackSegment",
            X = 120,
            Y = 24,
            Rotation = 0
        };

        layout.Elements.Add(fromBlock);
        layout.Elements.Add(toBlock);
        layout.Elements.Add(connector);

        layout.Routes.Add(new RouteDefinition
        {
            Id = "legacy-r",
            Name = "Legacy",
            FromBlockId = "b-from",
            ToBlockId = "b-to",
            FromBlockDirection = "Forward",
            ToBlockDirection = "Backward",
            StartNavigationDirection = "Diagonal",
            SafetyFallbackAspect = "UnsupportedAspect"
        });

        var vm = new RoutesManagerViewModel(settings);
        var route = Assert.Single(layout.Routes);
        var vmRoute = Assert.Single(vm.Routes);

        Assert.Equal(RouteDirection.Right, route.FromBlockDirection);
        Assert.Equal(RouteDirection.Left, route.ToBlockDirection);
        Assert.Equal(RouteDirection.Right, route.StartNavigationDirection);
        Assert.Equal("Stop", route.SafetyFallbackAspect);
        Assert.Single(route.RouteSignalIds);
        Assert.Equal("sig-right", route.RouteSignalIds[0]);

        Assert.Equal(RouteDirection.Right, vmRoute.FromBlockDirection);
        Assert.Equal(RouteDirection.Left, vmRoute.ToBlockDirection);
        Assert.Equal(RouteDirection.Right, vmRoute.StartNavigationDirection);
        Assert.Equal("Stop", vmRoute.SafetyFallbackAspect);
    }
}


