using System;
using System.Collections.Generic;
using System.Linq;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Shapes;
using Avalonia.Input;
using Avalonia.Media;
using Avalonia.Markup.Xaml;
using TrackFlow.Models.Layout;
using TrackFlow.ViewModels.Editor;
using TrackFlow.Views.Editor.Markers;

namespace TrackFlow.Views.Editor;

public partial class RoutePreviewControl : UserControl
{
    private const double Cell = LayoutEditorViewModel.CellSize;
    private const double DimmedOpacity = 0.18;

    private TrackLayout? _layout;
    private RouteItemVm? _selectedRoute;
    private readonly HashSet<string> _highlightedElementIds = new();
    private string? _manualStartBlockId;
    private string? _manualEndBlockId;

    /// <summary>Mapuje TurnoutId → požadovaný stav pre vybranú cestu.</summary>
    private readonly Dictionary<string, TurnoutState> _routeTurnoutStates = new();

    /// <summary>Aktuálny zoom faktor; null = "fit to window".</summary>
    private double? _zoomFactor = 1.0;

    public RoutePreviewControl()
    {
        AvaloniaXamlLoader.Load(this);
    }

    public event Action<string>? BlockClicked;

    public void SetLayoutAndRoute(
        TrackLayout? layout,
        RouteItemVm? selectedRoute,
        string? manualStartBlockId = null,
        string? manualEndBlockId = null)
    {
        _layout = layout;
        _selectedRoute = selectedRoute;
        _manualStartBlockId = manualStartBlockId;
        _manualEndBlockId = manualEndBlockId;

        _highlightedElementIds.Clear();
        _routeTurnoutStates.Clear();
        if (selectedRoute != null && layout != null)
        {
            _highlightedElementIds.Add(selectedRoute.FromBlockId);
            _highlightedElementIds.Add(selectedRoute.ToBlockId);

            foreach (var ts in selectedRoute.TurnoutSettings)
            {
                _highlightedElementIds.Add(ts.TurnoutId);
                _routeTurnoutStates[ts.TurnoutId] = ts.RequiredState;
            }

            foreach (var id in selectedRoute.PathElementIds)
                _highlightedElementIds.Add(id);
        }

        UpdateRouteKindBadge();
        RenderLayout();
        ApplyZoom();
    }

    private void UpdateRouteKindBadge()
    {
        var badge = this.FindControl<Border>("RouteKindBadge");
        var badgeText = this.FindControl<TextBlock>("RouteKindBadgeText");
        if (badge == null || badgeText == null)
            return;

        if (_selectedRoute == null)
        {
            badge.IsVisible = false;
            badgeText.Text = string.Empty;
            return;
        }

        if (_selectedRoute.Kind == RouteDefinitionKind.AutoGeneratedPath)
        {
            badge.Background = Brush.Parse("#ECEFF1");
            badge.BorderBrush = Brush.Parse("#B0BEC5");
            badgeText.Foreground = Brush.Parse("#37474F");
            badgeText.Text = "⚙ AUTO";
        }
        else
        {
            badge.Background = Brush.Parse("#E8F5E9");
            badge.BorderBrush = Brush.Parse("#A5D6A7");
            badgeText.Foreground = Brush.Parse("#1B5E20");
            badgeText.Text = "✍ MANUÁL";
        }

        badge.IsVisible = true;
    }

    // ─── ZOOM ────────────────────────────────────────────────────────────────
    private void ZoomCombo_SelectionChanged(object? sender, SelectionChangedEventArgs e)
    {
        if (sender is not ComboBox cb || cb.SelectedItem is not ComboBoxItem item) return;
        var tag = item.Tag?.ToString();
        if (tag == "fit")
            _zoomFactor = null;
        else if (double.TryParse(tag, System.Globalization.NumberStyles.Any,
                     System.Globalization.CultureInfo.InvariantCulture, out var z))
            _zoomFactor = z;
        ApplyZoom();
    }

    private void PreviewArea_SizeChanged(object? sender, SizeChangedEventArgs e)
    {
        if (_zoomFactor == null) ApplyZoom();
    }

    private void ApplyZoom()
    {
        var canvas = this.FindControl<Canvas>("LayoutCanvas");
        var scroller = this.FindControl<ScrollViewer>("PreviewScroller");
        if (canvas == null || scroller == null) return;

        double contentW = canvas.Width;
        double contentH = canvas.Height;
        if (contentW <= 0 || contentH <= 0) return;

        double zoom = _zoomFactor ?? ComputeFitZoom(contentW, contentH, scroller.Bounds.Size);
        if (zoom <= 0 || double.IsNaN(zoom) || double.IsInfinity(zoom)) zoom = 1.0;

        canvas.RenderTransform = new ScaleTransform(zoom, zoom);
        canvas.RenderTransformOrigin = new RelativePoint(0, 0, RelativeUnit.Relative);

        // Aby ScrollViewer videl správnu veľkosť po skalovaní:
        canvas.Margin = new Thickness(0, 0,
            Math.Max(0, contentW * (zoom - 1)),
            Math.Max(0, contentH * (zoom - 1)));
    }

    private static double ComputeFitZoom(double contentW, double contentH, Size viewport)
    {
        if (viewport.Width < 10 || viewport.Height < 10) return 1.0;
        double zx = (viewport.Width - 8) / contentW;
        double zy = (viewport.Height - 8) / contentH;
        return Math.Min(zx, zy);
    }

    // ─── RENDERING (mirroruje LayoutEditorView) ──────────────────────────────
    private void RenderLayout()
    {
        var canvas = this.FindControl<Canvas>("LayoutCanvas");
        if (canvas == null) return;
        canvas.Children.Clear();

        if (_layout == null || _layout.Elements.Count == 0)
        {
            canvas.Width = 100;
            canvas.Height = 100;
            return;
        }

        // Bounding box pre offset – kreslíme od (0,0)
        double minX = _layout.Elements.Min(e => e.X);
        double minY = _layout.Elements.Min(e => e.Y);
        const double pad = Cell;

        double maxX = 0, maxY = 0;

        // 1. prechod: všetko OKREM blokov
        foreach (var el in _layout.Elements)
        {
            if (el.MarkerKey == "Block") continue;
            var ctrl = CreateMarkerControl(el);
            if (ctrl == null) continue;

            // Pre výhybky na vybranej ceste vyfarbíme správne podľa požadovaného stavu.
            if (el is TurnoutElement && _routeTurnoutStates.TryGetValue(el.Id, out var requiredState))
                ApplyTurnoutStateColoring(ctrl, el, requiredState);
            // Pre CELÉ neaktívne výhybky (nie sú na ceste) stlmíme aj outline vrstvy.
            else if (el is TurnoutElement)
                DimTurnoutOutlines(ctrl);

            ApplyHighlight(ctrl, el, isBlock: false);
            Canvas.SetLeft(ctrl, el.X - minX + pad);
            Canvas.SetTop(ctrl, el.Y - minY + pad);
            canvas.Children.Add(ctrl);

            maxX = Math.Max(maxX, el.X - minX + pad + Cell);
            maxY = Math.Max(maxY, el.Y - minY + pad + Cell);
        }

        // 2. prechod: bloky navrchu (rovnako ako v editore)
        foreach (var el in _layout.Elements)
        {
            if (el.MarkerKey != "Block") continue;
            var state = ResolveBlockHighlightState(el.Id);
            var ctrl = CreateBlockControl(el, state);
            if (ctrl == null) continue;
            ctrl.Tag = el.Id;
            ctrl.PointerPressed += OnBlockPointerPressed;
            ApplyHighlight(ctrl, el, isBlock: true);
            Canvas.SetLeft(ctrl, el.X - minX + pad);
            Canvas.SetTop(ctrl, el.Y - minY + pad);
            canvas.Children.Add(ctrl);

            int len = (el is BlockElement be) ? Math.Clamp(be.BlockLengthCells, 1, 20) : 4;
            bool vert = el.Rotation == 90 || el.Rotation == 270;
            double w = vert ? Cell : Cell * len;
            double h = vert ? Cell * len : Cell;
            maxX = Math.Max(maxX, el.X - minX + pad + w);
            maxY = Math.Max(maxY, el.Y - minY + pad + h);
        }

        canvas.Width = maxX + pad;
        canvas.Height = maxY + pad;
    }

    private BlockHighlightState ResolveBlockHighlightState(string blockId)
    {
        if (!string.IsNullOrWhiteSpace(_manualStartBlockId)
            && string.Equals(blockId, _manualStartBlockId, StringComparison.OrdinalIgnoreCase))
            return BlockHighlightState.ManualStart;

        if (!string.IsNullOrWhiteSpace(_manualEndBlockId)
            && string.Equals(blockId, _manualEndBlockId, StringComparison.OrdinalIgnoreCase))
            return BlockHighlightState.ManualEnd;

        return _highlightedElementIds.Contains(blockId)
            ? BlockHighlightState.Route
            : BlockHighlightState.None;
    }

    private void OnBlockPointerPressed(object? sender, PointerPressedEventArgs e)
    {
        if (sender is not Control ctrl)
            return;
        if (ctrl.Tag is not string blockId || string.IsNullOrWhiteSpace(blockId))
            return;

        BlockClicked?.Invoke(blockId);
        e.Handled = true;
    }

    /// <summary>Aplikuje opacity + farebný glow pre prvky na ceste.</summary>
    private void ApplyHighlight(Control ctrl, LayoutElement el, bool isBlock)
    {
        bool highlighted = _highlightedElementIds.Contains(el.Id);

        // Bloky musia byť VŽDY plne nepriehľadné, aby prekryli koľaje za sebou.
        // "Stmavnutie" pre nezvýraznené bloky robíme šedou výplňou v CreateBlockControl.
        if (!isBlock)
            ctrl.Opacity = highlighted ? 1.0 : DimmedOpacity;
        else
            ctrl.Opacity = 1.0;

        if (highlighted && _selectedRoute != null)
        {
            var color = TryParseColor(_selectedRoute.Color);
            ctrl.Effect = new DropShadowEffect
            {
                Color = color,
                BlurRadius = 10,
                OffsetX = 0,
                OffsetY = 0,
                Opacity = 1.0
            };
        }
        else
        {
            ctrl.Effect = null;
        }
    }

    private static Color TryParseColor(string s)
    {
        if (string.IsNullOrWhiteSpace(s)) return Color.FromRgb(0, 212, 170);
        try { return Color.Parse(s); } catch { return Color.FromRgb(0, 212, 170); }
    }

    /// <summary>
    /// Pre celé neaktívne výhybky upraví farbu AXAML outline aby zodpovedala TrackSegment.
    /// </summary>
    private static void DimTurnoutOutlines(Control host)
    {
        if (host is not Grid grid) return;
        
        // Výhybky nemajú dvojitý outline, len jeden UserControl s AXAML outline vrstvami vnútri.
        UserControl? marker = null;
        foreach (var child in grid.Children)
        {
            if (child is UserControl uc) { marker = uc; break; }
        }
        if (marker?.Content is not Canvas canvas) return;

        // Outline vrstvy prepíšeme na rovnakú farbu ako TrackSegment (pred aplikovaním opacity).
        var trackOutlineBrush = new SolidColorBrush(Color.FromArgb(204, 0, 0, 0));
        
        foreach (var child in canvas.Children)
        {
            if (child is Shape shape && shape.Name?.Contains("Outline") == true)
                shape.Stroke = trackOutlineBrush;
        }
    }

    /// <summary>
    /// Vyfarbí výhybku tak, aby ukazovala požadovaný stav (Straight/Diverge/...).
    /// Aktívna vetva = modrá a ide navrch (ZIndex), neaktívna vetva = sivá vzadu.
    ///
    /// DÔLEŽITÉ: Identifikácia vetvy je striktne podľa <c>x:Name</c> v AXAML
    /// markera, NIE podľa orientácie čiary – orientácia sa po rotácii markera
    /// mení a viedla by k nesprávnemu zafarbeniu.
    ///
    /// Konvencia mien (zhodná s AXAML markerov):
    ///   Turnout_L / R / L90 / R90 : StraightLine = priama,  CurvePath = odbočka
    ///   TurnoutCurve_L / R        : Arc1Path     = priama,  Arc2Path  = odbočka
    ///   Turnout_Y                 : Arc1Path     = ľavá,    Arc2Path  = pravá
    ///   Turnout_3W                : CenterLine   = priama,  ArcLPath  = vľavo, ArcRPath = vpravo
    /// </summary>
    private static void ApplyTurnoutStateColoring(Control host, LayoutElement el, TurnoutState state)
    {
        if (host is not Grid grid || grid.Children.Count == 0) return;

        // Vrchnú vrstvu (farebný marker) nájdeme ako posledný UserControl v Grid-e.
        UserControl? marker = null;
        for (int i = grid.Children.Count - 1; i >= 0; i--)
        {
            if (grid.Children[i] is UserControl uc) { marker = uc; break; }
        }
        if (marker?.Content is not Canvas canvas) return;

        var blue = new SolidColorBrush(Color.Parse("#71c5ff"));
        // Neaktívne vetvy si ponechajú pôvodnú farbu z AXAML (bielu #FFFFFF),
        // ako pri neaktívnych koľajniciach - len sa stlmia opacity.

        bool IsBranchActive(string name) => el.MarkerKey switch
        {
            "Turnout_L" or "Turnout_R" or "TurnoutL90" or "TurnoutR90" => name switch
            {
                "StraightLine" => state == TurnoutState.Straight,
                "CurvePath"    => state is TurnoutState.Diverge
                                       or TurnoutState.DivergeLeft
                                       or TurnoutState.DivergeRight,
                _ => false
            },
            "TurnoutCurve_L" or "TurnoutCurve_R" => name switch
            {
                "Arc1Path" => state == TurnoutState.Straight,
                "Arc2Path" => state is TurnoutState.Diverge
                                    or TurnoutState.DivergeLeft
                                    or TurnoutState.DivergeRight,
                _ => false
            },
            "Turnout_Y" => name switch
            {
                "Arc1Path" => state is TurnoutState.DivergeLeft or TurnoutState.Straight,
                "Arc2Path" => state is TurnoutState.DivergeRight or TurnoutState.Diverge,
                _ => false
            },
            "Turnout_3W" => name switch
            {
                "CenterLine" => state == TurnoutState.Straight,
                "ArcLPath"   => state == TurnoutState.DivergeLeft,
                "ArcRPath"   => state == TurnoutState.DivergeRight,
                _ => false
            },
            _ => false
        };

        foreach (var child in canvas.Children)
        {
            if (child is not Shape shape) continue;

            var name = shape.Name;
            if (string.IsNullOrEmpty(name)) continue;

            // Outline vrstvy nedotýkať – len farebné vrstvy na vrchu.
            if (name.Contains("Outline")) continue;

            bool active = IsBranchActive(name);

            // Aktívna vetva = modrá, neaktívna ponechá pôvodnú farbu z AXAML.
            if (active)
            {
                shape.Stroke = blue;
                shape.StrokeThickness = 2.5;
            }
            else
            {
                // Neaktívna vetva: ponechať pôvodnú farbu, len upraviť hrúbku.
                // Farba zostáva tá z AXAML (#FFFFFF pre neaktívne vetvy).
                shape.StrokeThickness = 2.0;
            }

            // Neaktívna vetva má rovnakú opacity ako neaktívne koľajnice (0.18).
            shape.Opacity = active ? 1.0 : DimmedOpacity;

            // Aktívna vetva musí byť vpredu (prekryje neaktívnu).
            shape.ZIndex = active ? 20 : 1;
        }

        // Outline aktívnej vetvy posunieme tesne pod ňu, neaktívne outline prepíšeme
        // na rovnakú farbu ako TrackSegment aby po aplikovaní opacity mali rovnaký odtieň.
        var trackOutlineBrush = new SolidColorBrush(Color.FromArgb(204, 0, 0, 0));
        
        foreach (var child in canvas.Children)
        {
            if (child is not Shape shape) continue;
            var name = shape.Name;
            if (string.IsNullOrEmpty(name) || !name.Contains("Outline")) continue;

            // Odvodíme názov hlavnej vrstvy odstránením suffixu "Outline"
            var mainName = name.Replace("Outline", "");
            bool active = IsBranchActive(mainName);
            
            shape.ZIndex = active ? 19 : 0;
            
            if (active)
            {
                // Aktívna outline vrstva - plná čierna s výraznou hrúbkou.
                shape.StrokeThickness = 4.0;
                shape.Opacity = 1.0;
            }
            else
            {
                // Neaktívne outline prepíšeme na TrackSegment farbu a aplikujeme opacity.
                shape.Stroke = trackOutlineBrush;
                shape.StrokeThickness = 3.1;
                shape.Opacity = DimmedOpacity;
            }
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Renderovacia logika prekopírovaná 1:1 z LayoutEditorView – aby výsledný
    // vzhľad bol identický s editorom (vrátane rotácií, outline a 2-prechodu).
    // ════════════════════════════════════════════════════════════════════════

    private static Control? CreateMarkerControl(LayoutElement el)
    {
        // Pre výhybky NEVYTVÁRAME innerOutline - majú vlastné outline vrstvy v AXAML.
        bool isTurnout = el.MarkerKey.Contains("Turnout") || el.MarkerKey == "DoubleSlip";
        
        Control? innerOutline = isTurnout ? null : CreateMarkerByKey(el.MarkerKey);
        Control? inner = CreateMarkerByKey(el.MarkerKey);
        if (inner == null) return null;

        if (innerOutline != null)
        {
            innerOutline.UseLayoutRounding = false;
            if (innerOutline is UserControl ucO)
            {
                ucO.HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Left;
                ucO.VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top;
            }
            if (innerOutline is IMarkerAngle mO)
                mO.SetAngle((int)el.Rotation);
            else if (el.Rotation != 0)
                innerOutline.RenderTransform = new RotateTransform(el.Rotation, Cell / 2, Cell / 2);
            ApplyOutlineStyle(innerOutline, el);
        }

        inner.UseLayoutRounding = false;
        if (inner is UserControl uc)
        {
            uc.HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Left;
            uc.VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top;
        }
        if (inner is IMarkerAngle m)
            m.SetAngle((int)el.Rotation);
        else if (el.Rotation != 0)
            inner.RenderTransform = new RotateTransform(el.Rotation, Cell / 2, Cell / 2);

        var host = new Grid
        {
            Width = Cell,
            Height = Cell,
            HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Left,
            VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top,
            UseLayoutRounding = false,
            ClipToBounds = false,
        };
        if (innerOutline != null) host.Children.Add(innerOutline);
        host.Children.Add(inner);
        return host;
    }

    private static Control? CreateMarkerByKey(string key) => key switch
    {
        "TrackSegment"   => new MarkerTrackSegment(),
        "Curve_45"       => new MarkerCurve45(),
        "Curve_90"       => new MarkerCurve90(),
        "Bumper"         => new MarkerBumper(),
        "Turnout_L"      => new MarkerTurnoutL(),
        "Turnout_R"      => new MarkerTurnoutR(),
        "TurnoutL90"     => new MarkerTurnoutL90(),
        "TurnoutR90"     => new MarkerTurnoutR90(),
        "TurnoutCurve_L" => new MarkerTurnoutCurveL(),
        "TurnoutCurve_R" => new MarkerTurnoutCurveR(),
        "Turnout_Y"      => new MarkerTurnoutY(),
        "Turnout_3W"     => new MarkerTurnout3W(),
        "Cross90"        => new MarkerCross90(),
        "Cross45"        => new MarkerCross45(),
        "DoubleSlip"     => new MarkerDoubleSlip(),
        "Bridge90"       => new MarkerBridge90(),
        "Bridge45L"      => new MarkerBridge45L(),
        "Bridge45R"      => new MarkerBridge45R(),
        "Signal" or "Signal5" or "Signal4" or "Signal2Main" or "Signal2Shunt" or "Signal2Route" or "Signal3Entry" => new MarkerSignal(),
        "Sensor"         => new MarkerSensor(),
        "Route"          => new MarkerRoute(),
        _ => null
    };

    private static void ApplyOutlineStyle(Control marker, LayoutElement el)
    {
        // Pre výhybky NEAPLIKUJEME dynamický outline - majú vlastné outline vrstvy v AXAML.
        // Tie sa upravia v DimTurnoutOutlines alebo ApplyTurnoutStateColoring.
        bool isTurnout = el.MarkerKey.Contains("Turnout") || el.MarkerKey == "DoubleSlip";
        if (isTurnout) return;
        
        if (marker is not UserControl uc) return;
        if (uc.Content is Canvas canvas)
        {
            foreach (var child in canvas.Children)
            {
                if (child is Shape shape && shape.Tag?.ToString() == "NoOutline") continue;
                if (child is Control ctrl && ctrl.Name?.Contains("Outline") == true) continue;

                if (child is Line line)
                {
                    line.StrokeThickness += 2;
                    line.Stroke = new SolidColorBrush(Color.FromArgb(204, 0, 0, 0));
                }
                else if (child is Path path)
                {
                    path.StrokeThickness += 2;
                    path.Stroke = new SolidColorBrush(Color.FromArgb(204, 0, 0, 0));
                }
            }
        }
        else if (uc.Content is Path pathDirect)
        {
            pathDirect.StrokeThickness += 2;
            pathDirect.Stroke = new SolidColorBrush(Color.FromArgb(204, 0, 0, 0));
        }
    }

    private static Control CreateBlockControl(LayoutElement el, BlockHighlightState highlightState)
    {
        int blockLengthCells = 4;
        if (el is BlockElement blockEl)
            blockLengthCells = Math.Clamp(blockEl.BlockLengthCells, 1, 20);

        bool isVertical = el.Rotation == 90 || el.Rotation == 270;
        double W = isVertical ? Cell : Cell * blockLengthCells;
        double H = isVertical ? Cell * blockLengthCells : Cell;

        string blockName = string.IsNullOrWhiteSpace(el.Label) ? "Blok" : el.Label;

        var canvas = new Canvas
        {
            Width = W,
            Height = H,
            ClipToBounds = false,
            UseLayoutRounding = false,
        };

        var fill = highlightState switch
        {
            BlockHighlightState.ManualStart => new SolidColorBrush(Color.Parse("#E8F4FF")),
            BlockHighlightState.ManualEnd => new SolidColorBrush(Color.Parse("#F6E8FF")),
            BlockHighlightState.Route => new SolidColorBrush(Color.Parse("#FFFFDC")),
            _ => new SolidColorBrush(Color.Parse("#E8E8E8"))
        };
        var stroke = highlightState switch
        {
            BlockHighlightState.ManualStart => new SolidColorBrush(Color.Parse("#1565C0")),
            BlockHighlightState.ManualEnd => new SolidColorBrush(Color.Parse("#6A1B9A")),
            BlockHighlightState.Route => new SolidColorBrush(Color.Parse("#003366")),
            _ => new SolidColorBrush(Color.Parse("#A0A0A0"))
        };
        var textColor = highlightState == BlockHighlightState.None
            ? new SolidColorBrush(Color.Parse("#909090"))
            : new SolidColorBrush(Color.Parse("#333333"));

        var rect = new Rectangle
        {
            Width = W,
            Height = H,
            Fill = fill,
            Stroke = stroke,
            StrokeThickness = 1,
            RadiusX = 2,
            RadiusY = 2,
            UseLayoutRounding = false,
        };
        Canvas.SetLeft(rect, 0);
        Canvas.SetTop(rect, 0);
        canvas.Children.Add(rect);

        const double TextH = 14.0;
        var text = new TextBlock
        {
            Text = blockName,
            FontSize = 12,
            FontWeight = FontWeight.Normal,
            Foreground = textColor,
            TextAlignment = Avalonia.Media.TextAlignment.Center,
        };

        if (!isVertical)
        {
            text.Width = W;
            Canvas.SetLeft(text, 0);
            Canvas.SetTop(text, (H - TextH) / 2);
        }
        else
        {
            text.Width = H;
            text.Height = TextH;
            text.RenderTransform = new RotateTransform(el.Rotation == 90 ? 90 : -90);
            text.RenderTransformOrigin = new RelativePoint(0.5, 0.5, RelativeUnit.Relative);
            Canvas.SetLeft(text, W / 2 - H / 2);
            Canvas.SetTop(text, H / 2 - TextH / 2);
        }
        canvas.Children.Add(text);

        return canvas;
    }

    private enum BlockHighlightState
    {
        None,
        Route,
        ManualStart,
        ManualEnd
    }
}











